package commands

// OpenWRT/procd service backend. The cross-platform github.com/kardianos/service
// library does not support procd (OpenWRT's init/process manager), so on such a
// system we manage a native /etc/init.d/decenzed-node procd script ourselves.
// This keeps `decenzed-node service …` working on a router exactly like on a
// systemd/Windows host. The detection is a no-op (returns false) on every other
// platform, so this file compiles and links everywhere without build tags.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
)

const (
	procdInitPath = "/etc/init.d/decenzed-node"
	procdPidFile  = "/var/run/decenzed-node.pid"
)

// procdAvailable reports whether we are on OpenWRT (managed by procd), so we use
// the procd backend instead of kardianos. It requires BOTH the procd binary and
// the OpenWRT release marker: /sbin/procd exists only on OpenWRT, and
// /etc/openwrt_release is a definitive OpenWRT marker. A systemd Linux desktop
// has neither; macOS has an /etc/rc.common but no /sbin/procd — so nothing but a
// real OpenWRT device matches. Kept as a plain file check (no build tags) so the
// file compiles and links on every platform.
func procdAvailable() bool {
	for _, p := range []string{"/sbin/procd", "/etc/openwrt_release"} {
		if _, err := os.Stat(p); err != nil {
			return false
		}
	}
	return true
}

// resolvedExePath returns the absolute, symlink-resolved path to this binary so
// the service invokes the real file (an install may expose it via a
// /usr/bin/decenzed-node symlink).
func resolvedExePath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	if r, e := filepath.EvalSymlinks(exe); e == nil {
		exe = r
	}
	return exe, nil
}

func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// procdInitScript renders the /etc/init.d init script. exe is the binary to run;
// data (when non-empty) is passed as DECENZED_DATA so the daemon uses the same
// data directory the CLI resolved at install time.
func procdInitScript(exe, data string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh /etc/rc.common\n")
	b.WriteString("# decenzed-node — auto-generated by 'decenzed-node service install'. Do not edit.\n")
	b.WriteString("USE_PROCD=1\n")
	b.WriteString("START=95\n")
	b.WriteString("STOP=10\n\n")
	fmt.Fprintf(&b, "PROG=%s\n", shellSingleQuote(exe))
	fmt.Fprintf(&b, "DATA=%s\n\n", shellSingleQuote(data))
	b.WriteString("start_service() {\n")
	b.WriteString("\tprocd_open_instance\n")
	b.WriteString("\tprocd_set_param command \"$PROG\" start\n")
	b.WriteString("\t[ -n \"$DATA\" ] && procd_set_param env DECENZED_DATA=\"$DATA\"\n")
	b.WriteString("\tprocd_set_param respawn 3600 5 5\n")
	b.WriteString("\tprocd_set_param stdout 1\n")
	b.WriteString("\tprocd_set_param stderr 1\n")
	fmt.Fprintf(&b, "\tprocd_set_param pidfile %s\n", procdPidFile)
	b.WriteString("\tprocd_close_instance\n")
	b.WriteString("}\n")
	return b.String()
}

// procdCtl runs an /etc/init.d/decenzed-node action, streaming its output.
func procdCtl(action string) error {
	cmd := exec.Command(procdInitPath, action)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// cmdServiceProcd implements `service …` on OpenWRT via a procd init script.
func cmdServiceProcd(args []string) error {
	switch args[0] {
	case "install":
		c, cErr := loadConfig()
		if cErr != nil || c.RealityPublicKey == "" {
			return fmt.Errorf("run 'setup' first")
		}
		exe, err := resolvedExePath()
		if err != nil {
			return err
		}
		dir, err := dataDir()
		if err != nil {
			return err
		}
		if err := os.WriteFile(procdInitPath, []byte(procdInitScript(exe, dir)), 0o755); err != nil {
			return fmt.Errorf("write %s (needs root): %w", procdInitPath, err)
		}
		if err := procdCtl("enable"); err != nil {
			return fmt.Errorf("enable service: %w", err)
		}
		// Start fresh, but avoid `restart`/`stop` on a not-yet-registered service:
		// procd prints a scary (harmless) "ubus ... service delete: Not found" then.
		// Only stop when it is actually running (i.e. a reinstall over a live one).
		if procdRunning() {
			_ = procdCtl("stop")
		}
		if err := procdCtl("start"); err != nil {
			return fmt.Errorf("start service: %w", err)
		}
		fmt.Println("installed and started via procd — runs on boot. Share with: decenzed-node link")
		return nil
	case "uninstall":
		_ = procdCtl("stop")
		_ = procdCtl("disable")
		if err := os.Remove(procdInitPath); err != nil && !os.IsNotExist(err) {
			return err
		}
		fmt.Println("uninstalled.")
		return nil
	case "start":
		return procdCtl("start")
	case "stop":
		return procdCtl("stop")
	case "restart":
		return procdCtl("restart")
	case "status":
		fmt.Println("service status:", procdStatusString())
		return nil
	default:
		return fmt.Errorf("service: unknown subcommand %q", args[0])
	}
}

// procdStatusString reports the service state on OpenWRT: "running", "stopped",
// or "unknown (not installed?)" when no init script is present.
func procdStatusString() string {
	if _, err := os.Stat(procdInitPath); err != nil {
		return "unknown (not installed?)"
	}
	if procdRunning() {
		return "running"
	}
	return "stopped"
}

// procdRunning checks the procd pidfile for a live process.
func procdRunning() bool {
	b, err := os.ReadFile(procdPidFile)
	if err != nil {
		return false
	}
	pid, err := strconv.Atoi(strings.TrimSpace(string(b)))
	if err != nil || pid <= 0 {
		return false
	}
	proc, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	// On Unix, signal 0 probes for existence without affecting the process.
	return proc.Signal(syscall.Signal(0)) == nil
}
